# Generated by Django 4.2 on 2023-05-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processing', '0002_remove_order_item'),
        ('base', '0019_cart_status_alter_cart_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_processing.order'),
        ),
    ]
