# Generated by Django 4.2 on 2023-05-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name_order',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='base.item'),
        ),
    ]
